# Generated by Django 5.0.6 on 2024-06-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('done', 'done')], default='new'),
        ),
    ]
